import Head from "next/head";
import Intro from "../components/Intro";
import Solutions from "../components/Solutions";

import How from "../components/How";
import Costumers from "../components/costumers";
import SuccessCases from "../components/SuccessCases";
import Demo from "../components/Demo";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="font-Lato">
        <div className="bg-rw-main px-10 md:px-44">
          <div className="flex justify-between mx-4">
            <Image
              alt="logo"
              src="/Logo.png"
              width={241}
              height={99}
              layout="responsive"
              placeholder="empty"
            />
            <div>
              <Link href="/company">
                <button className="mx-2 text-white">Compañia</button>
              </Link>
      
                <button className="w-40 h-16 bg-rw-light text-white">
                  Contactanos
                </button>
        
            </div>
          </div>

          <Intro />
          <Solutions />
        </div>
        <How />
        <Costumers />
        <SuccessCases />
        <Demo />
      </main>

      <footer></footer>
    </div>
  );
}
